<a href="https://colab.research.google.com/github/dbtjr1103/Basic_practice/blob/main/%ED%8A%B9%EC%84%B1%EA%B3%B5%ED%95%99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

perch = pd.read_csv("perch.csv")
target = perch['weight'].to_numpy()
target

array([   5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
        685. ,  700. ,  700. ,  690. ,  900. ,  650. ,  820. ,  850. ,
        900. , 1015. ,  820. , 1100. , 1000. , 1100. , 1000. , 1000. ])

In [2]:
perch2 = pd.read_csv("perch2.csv").to_numpy()
perch2

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94],
       [18.  ,  5.22,  3.32],
       [18.7 ,  5.2 ,  3.12],
       [19.  ,  5.64,  3.05],
       [19.6 ,  5.14,  3.04],
       [20.  ,  5.08,  2.77],
       [21.  ,  5.69,  3.56],
       [21.  ,  5.92,  3.31],
       [21.  ,  5.69,  3.67],
       [21.3 ,  6.38,  3.53],
       [22.  ,  6.11,  3.41],
       [22.  ,  5.64,  3.52],
       [22.  ,  6.11,  3.52],
       [22.  ,  5.88,  3.52],
       [22.  ,  5.52,  4.  ],
       [22.5 ,  5.86,  3.62],
       [22.5 ,  6.79,  3.62],
       [22.7 ,  5.95,  3.63],
       [23.  ,  5.22,  3.63],
       [23.5 ,  6.28,  3.72],
       [24.  ,  7.29,  3.72],
       [24.  ,  6.38,  3.82],
       [24.6 ,  6.73,  4.17],
       [25.  ,  6.44,  3.68],
       [25.6 ,  6.56,  4.24],
       [26.5 ,  7.17,  4.14],
       [27.3 ,  8.32,  5.14],
       [27.5 ,  7.17,  4.34],
       [27.5 ,  7.05,  4.34],
       [27

In [4]:
perch2.shape

(56, 3)

In [6]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias = False) #1로만 되어있는 필요없는 특성
perch_poly = poly.fit_transform(perch2)

In [8]:
perch_poly.shape 
#x1, x2, x3  + 각각의 제곱 + x1x2, x1x3, x2x3

(56, 9)

In [9]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(perch_poly, target)

In [10]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
train_scaled = ss.fit_transform(train_input) # train_input의 평균, 표준편차를 학습해서 얻고, 변환해서 train_scaled에 넣어라
test_scaled = ss.transform(test_input) # 위에서 구했던 train_input의 평균, 표준편차로 변환해서 test_scaled에 넣어라


In [14]:
import numpy as np
np.std(train_scaled, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.mean(train_scaled, axis=0) # 표준화 완료

array([-3.17206578e-16,  9.62193288e-16,  2.80199144e-16,  2.32618158e-16,
        6.87280920e-17,  3.64787565e-16,  2.37904934e-17,  1.69176842e-16,
       -3.70074342e-17])

In [16]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(train_scaled, train_target)

LinearRegression()

In [17]:
lr.score(test_scaled, test_target)

0.9650933286259131

In [ ]:
# poly = PolynomialFeatures(include_bias = False, degree=5) # 5제곱까지 허용
# 너무 모델이 학습세트에 맞아버려서 정밀도 떨어짐
# 너무 특성을 많이 늘려버리면 안좋은 결과