<a href="https://colab.research.google.com/github/dbtjr1103/Basic_practice/blob/main/Day04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 18장 수치 계산 라이브러리 Numpy 알아보기
- 수치해석용 파이썬 패키지


In [1]:
# np.array : 행렬 변환
import numpy as np
array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)

# 병렬계산을 가능하게 해줌
print(array1 + 3)

# 2차원
array2 = np.array([[1,2,3], [4,5,6]])
print(type(array2))
print(array2.shape)

# ndim : 차원 확인
print(array1.ndim)
print(array2.ndim)

<class 'numpy.ndarray'>
(3,)
[4 5 6]
<class 'numpy.ndarray'>
(2, 3)
1
2


In [2]:
# 데이터 타입 확인 
import numpy as np
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

# 문자열이 포함되어있으면 모두 문자열로 바뀜
list2 = [1,2,3,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# 실수가 포함되어있으면 모두 실수로 바뀜 -> 메모리가 커짐
list3 = [1,2,3, 4.0]
array3 = np.array(list3)
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' '3' 'test'] <U21
[1. 2. 3. 4.] float64


In [3]:
# 데이터 타입 변환
import numpy as np
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int = np.array([1,2,3])
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.2,3.3])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [4]:
# np.arange : 행렬 편리하게 생성
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [5]:
# zeros : 0으로 채워진 행렬 만들기
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [6]:
# ones : 1로 채워진 행렬 만들기
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [7]:
# reshape : 차원바꾸기 (2차)
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5) #개수가 같아야 함
print('array2:\n',array2)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
# reshape : 차원바꾸기 (3차원)
array1 = np.arange(8)
print('array1:\n', array1)

array3d = array1.reshape(2,2,2) #개수가 같아야 함
print('array3d:\n',array3d.tolist()) #tolist 리스트로 다시 바꿔줌

array1:
 [0 1 2 3 4 5 6 7]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [9]:
# 인덱싱
array1 = np.arange(start=1, stop=10)
print(array1)

value = array1[2]
print(value)

value2 = array1[-2]
print(value2)

# 값 바꾸기
array1[0] = 9
array1[8] = 0
print(array1)

[1 2 3 4 5 6 7 8 9]
3
8
[9 2 3 4 5 6 7 8 0]


In [10]:
# 2차원 인덱싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0,0])
print(array2d[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
5


In [11]:
# 슬라이싱
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array3 = array1[1:4]
print(array3)
print(type(array3))

array5 = array1[3:]
array6 = array1[:]
print(array5)
print(array6)

[1 2 3]
[2 3 4]
<class 'numpy.ndarray'>
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [12]:
# 2차원 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0:2, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [13]:
# 불리언 인덱싱
array1d = np.arange(start=1, stop=10)
# []안에 array1d > Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [14]:
# 다른방법
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


In [15]:
# 행렬 정렬
org_array = np.array([3,1,9,5])
print("원본 행렬:",org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print( sort_array1)
print(org_array) # 실제로 원본을 정렬해주진않음, 진짜로 정렬하려면 sort함수로 정렬
sort_array2 = org_array.sort()
print(sort_array2) # 넣어주지못함
print(org_array)

원본 행렬: [3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [16]:
# 내림차순 정렬 
org_array = np.array([3,1,9,5])
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [17]:
# axis = 0 행방향, 1 열방향
array2d = np.array([[8,12], [7,1]])
print(array2d)
sort_array2d_axis0 = np.sort(array2d,axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d,axis=1)
print(sort_array2d_axis1)


[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [18]:
# agsort 정렬된 인덱스 가져오기 : 중요
org_array = np.array([3,1,9,5])

sort_indices = np.argsort(org_array)
print('행렬 정렬시 원본 행렬의 인덱스 :', sort_indices)
# 내림차순
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬시 원본 행렬의 인덱스 :', sort_indices_desc)

행렬 정렬시 원본 행렬의 인덱스 : [1 0 3 2]
행렬 내림차순 정렬시 원본 행렬의 인덱스 : [2 3 0 1]


In [19]:
# 행렬 내적
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [20]:
# 전치행렬 : 행과 열을 바꿈
A = np.array([[1,2,3],
              [3,4,5]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]
 [3 5]]


# 19장 판다스 소개 및 데이터 불러오기

**데이터분석** 

- 판다스 소개 및 데이터 불러오기
    - 판다스 라이브러리는 파이썬에서 데이터분석을 할 때 가장 많이 쓰이는 라이브러리
    - 표 형태의 데이터를 다루는 다양한 기능을 제공
    - 셀 병합이 없는 경우만 가능함

- 판다스
    1. 엑셀, CSV, pickle 등 다양한 데이터 형식을 지원
    2. 결측치 처리 기능
    3. 데이터 형태 바꾸기 (머신러닝)
    4. 데이터 삭제 및 추가
    5. 그룹화, 정렬, 결합
    6. 시계열 데이터
    7. 문자열 및 날짜/시간 (처리)지원

- 데이터 가시화
    - 많은 그래프 처리 라이브러리와의 연동

- 판다스 불러오기
    - import pandas as pd

- CSV
    - 데이터 형태 CSV는 데이터를 콤마(,)로 구분한다.
    - 판다스의 read_csv() 함수를 사용한다.
        - read_csv("파일이름.csv")

- TSV
    - 데이터 형태 TSV는 데이터를 탭(Tab)으로 구분한다.
    - 판다스에서는 TSV파일을 읽어오는 함수는 따로 제공하지 않는다.
    - 하지만 판다스의 read_csv()함수를 사용하여 TSV 파일을 읽어올 수 있다.
        - read_csv("파일이름.tsv", sep='\t')
    

In [21]:
import pandas as pd

In [22]:
pd.read_csv("concat_1.csv", sep=',')

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [23]:
pd.read_csv("gapminder.tsv", sep ='\t')

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [24]:
# 파일을 생성 / 불러오는 함수
f = open("test.txt", 'wt') # write text
f.write("hello")
f.close() # 저장하고 끄는 기능

In [25]:
f = open("test.txt", 'rt') # read text

data = f.read()

f.close()

In [26]:
data

'hello'

In [27]:
# 이어서 쓰는 기능
f = open("test.txt", 'at') # attach text
f.write("hello world")
f.close() # 저장하고 끄는 기능

# 20장 시리즈와 데이터프레임 이해하기

- 시리즈
    - 데이터프레임에서 각각의 열을 시리즈라고 한다.
    - 판다스의 pd.Series() 함수를 사용하여 시리즈를 생성할 수 있다

- 딕셔너리를 사용해서 시리즈 만들기
    ```
    dic = {"a":1, "b":2, "c":3}
    pd.Series(dic)
    ```
- 리스트를 사용해서 시리즈 만들기
    ```
    box = ['홍길동', '이순신', '아이유']
    pd.Series(box)
    ```
    ```
    box = ['홍길동', '이순신', '아이유']
    pd.Series(box, index=['가','나','다'])
    type(s)
    ```
- 시리즈 행이름 확인
    ```
    s.index
    ```
- 시리즈 값 확인
    ```
    s.values
    ```
- 시리즈 값 확인
    ```
    dic = {"이름" : ['홍길동', '이순신', '아이유'],
            "성별" : ['남자', '남자', '여자'].
            "나이" : [40, 50, 20]}
    pd.DataFrame(dic)
    pd.DataFrame(dic, index = ['A','B','C']) # 행이름 변경
    pd.DataFrame(dic, index = ['A','B','C'], colums = ['성별', '나이', '이름']) # colums 변경
    ```
- 리스트로 데이터프레임 만들기
    ```
    - 데이터크롤링
    box = [['홍길동', '남자', 40], ['이순신', '남자', 50]. ['아이유', '여자', 20]}
    pd.DataFrame(box)
    pd.DataFrame(box, colums = ['이름', '성별', '나이']) # colums 변경
    ```
- 데이터 프레임 열 이름 확인
    ```
    df.columns
    ```
- 데이터프레임 행 이름 확인
    ```
    df.index
    ```

In [28]:
import pandas as pd

In [29]:
s = pd.Series([100, 200, 300], index=['A','B','C'])
s

A    100
B    200
C    300
dtype: int64

In [30]:
s.index

Index(['A', 'B', 'C'], dtype='object')

In [31]:
s.values # 리스트가 아니라, 행렬

array([100, 200, 300])

In [32]:
df = pd.DataFrame({
    "이름" : ['홍길동', '이순신', '강동원', '아이유'],
    "성별" : ['남자', '남자', '남자', '여자'],
    "나이" : [40, 50, 30, 20]
}, index=['가','나','다','라'], columns = ['성별', '나이', '이름'])

df

성별  나이   이름
가  남자  40  홍길동
나  남자  50  이순신
다  남자  30  강동원
라  여자  20  아이유

In [33]:
box = [['홍길동','남자',40], ['이순신','남자',50], ['아이유','여자',20]]
box

[['홍길동', '남자', 40], ['이순신', '남자', 50], ['아이유', '여자', 20]]

In [34]:
pd.DataFrame(box)

0   1   2
0  홍길동  남자  40
1  이순신  남자  50
2  아이유  여자  20

In [35]:
a= pd.DataFrame(box, columns=['이름','성별', '나이'])
a

이름  성별  나이
0  홍길동  남자  40
1  이순신  남자  50
2  아이유  여자  20

In [36]:
a.columns

Index(['이름', '성별', '나이'], dtype='object')

In [37]:
a.index

RangeIndex(start=0, stop=3, step=1)